### ISSUE TITLE
Cann't run the demo. Need other packages?

### ISSUE THREAD

**Issue by GianMeng** [tyuownu/nearest_frontier_planner#1]
Hello, after I compile the source code on Ubuntu 14.04, I cann't not run the demo in [Usage](https://github.com/tyuownu/nearest_frontier_planner).

And I cann't find the package navigation_stage and the launch file : tutorial3_icp_nfp.launch in package nearest_frontier_planner.

So I try to find out that the navigation_stage is the package of the algorithm [frontier_exploration](http://wiki.ros.org/frontier_exploration). However, it seems not contain the launch file : move_base_icpslam_5cm.launch.

So I want to ask could you please kindly tell me where to git these code or whether there is something wrong?

Thank you so much! @tyuownu

**Comment by tyuownu** [comment]
Hi, @GianMeng . Sorry for late.
This package's purpose is just to give an example to find the unknown area, and it's also need the navigation algorithm. And the given example depends on some other packages, such as:
navigation: algorithm for move, obstacle avoidance, path planning and etc.
navigation_tutorials: stage environment configures.
mrpt_slam: SLAM algorithm to build the map.

I have fuse this package and other algorithms to a package, named [micvision](https://github.com/tyuownu/micvision), have more simulation environment(stage, gazebo) and a more detail tutorials. Thanks！

**Comment by GianMeng** [comment]
Thanks for your answer! I will try it.
