### ISSUE TITLE
where is the launch file?

### ISSUE THREAD

**Issue by kzhao94** [tyuownu/nearest_frontier_planner#2]
[move_base_icpslam_5cm.launch] is neither a launch file in package [navigation_stage] nor is [navigation_stage] a launch file name

[tutorial3_icp_nfp.launch] is neither a launch file in package [nearest_frontier_planner] nor is [nearest_frontier_planner] a launch file name

**Comment by tyuownu** [comment]
Sorry, the project do not have maintenance for a long time. The launch file renamed and I forget update the readme.md. You can refer to the newest readme file. Thanks
